docs: force manual git push for SVG

diff --git a/.github/workflows/drawio.yml b/.github/workflows/drawio.yml
--- a/.github/workflows/drawio.yml
+++ b/.github/workflows/drawio.yml
@@ -26,7 +26,10 @@ jobs:
         run: |
           find . -name "*.svg" -exec cp {} . \;
           git status
-      - name: Commit exported images
-        uses: stefanzweifel/git-auto-commit-action@v5
-        with:
-          commit_message: "docs: Auto-export drawio to SVG"
+      - name: Commit and Push SVG
+        run: |
+          git config user.name "GitHub Action"
+          git config user.email "action@github.com"
+          git add *.svg
+          git commit -m "docs: Auto-export drawio to SVG" || echo "No changes to commit"
+          git push || echo "Push failed"
